node.default['ssmtp'] = {}
node.default['ssmtp']['root_user']
node.default['ssmtp']['mail_hub']
node.default['ssmtp']['rewrite_domain']
node.default['ssmtp']['hostname']
node.default['ssmtp']['from_line_override']
node.default['ssmtp']['use_tls']
node.default['ssmtp']['use_starttls']
node.default['ssmtp']['tls_cert']
node.default['ssmtp']['auth_user']
node.default['ssmtp']['auth_pass']
node.default['ssmtp']['auth_method']
